apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-spanner
  labels:
    app: mini-spanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-spanner
  template:
    metadata:
      labels:
        app: mini-spanner
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: mini-spanner
          image: index.docker.io/paxjryan/mini-spanner:latest
          ports:
            - containerPort: 8080
          args: []
          imagePullPolicy: Always